set shell := ["cmd.exe", "/c"]

c:
    cd C:\Users\Danie\OneDrive\Escritorio\RepositorioProyecto1\pa-proyecto-tauri\src-tauri && cargo run

build:
    cmake .
    make 
    rm -rf Makefile CMakeCache.txt cmake_install.cmake CMakeFiles liblibrerias.a


build-w:
    C:\Users\Danie\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\221.5080.224\bin\cmake\win\bin\cmake.exe --build C:\Users\Danie\OneDrive\Escritorio\RepositorioProyecto1\pa-proyecto-tauri\cpp\cmake-build-debug --target usuarios
